import glob
import json
import os
import pandas as pd
import re
import yaml


## config.yaml #####################################################################################
try:
    configfile: "config/config.yaml"
except:
    pass


## resources #######################################################################################

try:
    workflow.global_resources["io"]
except:
    workflow.global_resources["io"] = 8


## config ##########################################################################################

try:
    results = config["results"]
except:
    results = "results"


try:
    config["verbose"]
except:
    config["verbose"] = False
verbose = config["verbose"]


config["envs"] = {}
try:
    for path in glob.glob("workflow/envs/*.yml") + glob.glob("workflow/envs/*.yaml"):
        config["envs"][os.path.splitext(os.path.basename(path))[0]] = path
except:
    pass


if verbose:
    print("{:#^100}".format(" Config "))
    print(json.dumps(config, sort_keys=True, indent=4))


## Deployment settings #############################################################################
if verbose:
    print("{:#^100}".format(" Deployment Settings "))
    ##print(workflow)
    print(workflow.deployment_settings)
    ##print(workflow.deployment_settings.apptainer_prefix)
    ##print(workflow.deployment_settings.apptainer_args)


## include #########################################################################################

include: "rules/containers.smk"
include: "rules/tools.smk"


## rule all ########################################################################################

if verbose:
    print("{:#^100}".format(" Workflow "))


rule all:
    input:
        ## containers ##############################################################################
        # "containers/bedtools.sif",
        # "containers/samtools.sif",
        expand(
            "containers/{env}.sif",
            env=config["envs"].keys()
        ),

        ## tools ###################################################################################
        expand("{results}/bedtools/c.bed",
            results=results,
        ),

