echo "date: $(date)"
echo "hostname: $(hostname)"
echo "user: $(whoami)"
echo "shell: $SHELL"
echo "path: $PATH"
echo "pwd: $(pwd)"
echo -e "locale:\n$(locale)"
echo -e "conda info:\n$(conda info)"
echo -e "conda list:\n$(conda list)"
echo
